# Docker Compose file for FitTracker microservices

version: '3.8'
services:
  userdb:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - fittracker-net

networks:
  fittracker-net:
    driver: bridge